# Generated by Django 3.2.5 on 2021-12-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('classS', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('residence', models.BooleanField()),
                ('dateAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('compulsory', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndPoints.subject', verbose_name='teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.IntegerField()),
                ('confidenceLevel', models.IntegerField()),
                ('dateGenerated', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndPoints.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EndPoints.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField()),
                ('comment', models.CharField(max_length=50, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndPoints.grade')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndPoints.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndPoints.subject')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EndPoints.tests')),
            ],
        ),
    ]
