# Generated by Django 4.0 on 2021-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EndPoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='marks')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
