# Generated by Django 4.0 on 2021-12-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EndPoints', '0002_marksuploads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarksUploads',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='confidenceLevel',
        ),
    ]
